# .github/workflows/deploy.yml
name: Deploy to DreamHost via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          # Datos sensibles en Settings → Secrets
          server:   "sftp.dreamhost.com"
          username: ${{ secrets.DH_SFTP_USER }}
          password: ${{ secrets.DH_SFTP_PASS }}
          port:     22

          # Toma TODO lo que hay en la raíz de tu repo:
          local-dir:  ./

          # Carpeta destino en tu servidor DreamHost:
          server-dir: /home/dh_bfijv6/adsrestauraciones.com/

          # Lista de patrones a NO subir:
          exclude: '.git*,.github/,node_modules/,.DS_Store,.env'
